/**
 * Standard Station Expense Categories for Downstream Petroleum Retail Stations.
 * Pre-seeded from standard operational charts of accounts.
 */

export const STANDARD_STATION_EXPENSE_CATEGORIES = [
  'OTHER REPAIRS',
  'GENSET REPAIRS& MAINTENANCE',
  'PUMP REPAIRS& MAINTENANCE',
  'ROAD TRANSPORT LOCAL',
  'CLEANING & SANITATION',
  'DISEL FOR GENSET',
  'ECG',
  'WATER',
  'BOP',
  'FACTORIES INSPECTORATE',
  'STOOL LANDS',
  'FIRE',
  'EPA',
  'GSA',
  'REGULATORY EXPENSES',
  'STATIONARY',
  'DISCOUNT ON SALES',
  'FUNERAL DONATION',
  'ACCOMODATION',
  'SALARIES&SSNIT',
  'HEAD OFFICE FUEL TAKEN',
  'POLICE FUEL',
  'HEALTH&SAFETY',
  'SALES PROMOTION',
  'OFFICE FURNITURE',
  'DEALER COMMISSION',
  'HAULAGE CLAIMS',
  'OTHER EXPENSES',
  'TRANSPORTER FUEL',
  'VEHICLE RUNNING COST',
  'RETAIL OUTLET LICENSE',
  'DONATIONS',
  'STATION EXPENSES',
  'DEPOT EXPENSES',
  'DISCOUNT ALLOWED',
  'TREKKING EXPENSES - OPERATIONS',
  'BUSINESS PROMOTION',
] as const

export type StandardExpenseCategory = typeof STANDARD_STATION_EXPENSE_CATEGORIES[number]
